baseURL = 'https://antkazakovv.github.io/personal-page/'
languageCode = 'en-us'
title = 'Remi Page'
theme = 'terminal'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 1

  [[menu.main]]
    name = "Favorite Movies"
    url = "/movies/"
    weight = 2

  [[menu.main]]
    name = "IT Place"
    url = "/it-place/"
    weight = 3

  [[menu.main]]
    name = "My Anarchist Ideology"
    url = "/posts/my-anarchist-ideology"
    weight = 4
    

[params]
  centerTheme = true

[params.logo]
logoText = "$>_ REMI"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
