baseURL = 'http://0.0.0.0/personal-page/'
languageCode = 'en-us'
title = 'Remi Page'
theme = 'terminal'

[markup.goldmark.renderer]
unsafe = true

[menu]
  [[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 1

  [[menu.main]]
    name = "Favorite Movies"
    url = "/movies/"
    weight = 2

[params]
  centerTheme = true

[params.logo]
logoText = "$>_ REMI"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
