baseURL = 'https://antkazakovv.github.io/hugo-personal-page/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

[markup.goldmark.renderer]
unsafe = true


[menu]
  [[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 1

  [[menu.main]]
    name = "Favorite Movies"
    url = "/movies/"
    weight = 2

[params]
  centerTheme = true

[params.logo]
logoText = "Remi Page"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
